### ISSUE TITLE
`engines` in package.json prevent me from installing the package

### ISSUE THREAD

**Issue by rafaeleyng** [crccheck/redis-url-parse#9]
Hi there! First, thanks for the nice package 😄 

I would like to use your package but both `npm` and `yarn` will refuse to install because you specified [those engines](https://github.com/crccheck/redis-url-parse/blob/master/package.json#L14) on the package.json (I'm using node `v10.12.0`, just to illustrate).

Looking through the lib, I personally don't see any reason why narrow down to those particular engines, given it is pretty small and shouldn't need any particular feature from some particular verion. I suggest to remove the `engines` altogether.

Note: I know that `npm` supports [`engine-strict=false`](https://docs.npmjs.com/misc/config#engine-strict) and `yarn` supports [`--ignore-engines`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines), but in my company we tend to use Makefiles that try to detect `yarn` and use it, or fallback to `npm`, so adding that would quickly become cumbersome and tool-specific. Besides that, I honestly don't see any advantage in keeping the `engines`.

**Comment by crccheck** [comment]
good call. I don't do this style anymore and I'll update now

**Comment by rafaeleyng** [comment]
Nice! It would be awesome if you could ping me when 2.0.0 gets released to npm (I see that you just commited the version on the repo)

**Comment by crccheck** [comment]
Pushed now. Thanks for your patience 

https://www.npmjs.com/package/redis-url-parse
